name: "Build and deploy to microservice"

on:
  push:
    branches:
      - 'staging'

jobs:
  build: 
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.6.0
        with:
          node-version: 18
      - uses: unfor19/install-aws-cli-action@v1
      - uses: actions-hub/docker/cli@master
        env:
          SKIP_LOGIN: true
      - name: Build image
        run: npm run build-docker
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          REGION: eu-west-1
          IMAGE: jbtest:staging-${{github.run_number}}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  deployment:
    name: Deploy to microservice
    needs: build
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4.5.0
        with:
          python-version: 'pypy3.9'
      - name: Deploy
        run: npm run deploy
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          REGION: eu-west-1
          IMAGE: jbtest:staging-${{github.run_number}}
          MICROSERVICE: ${{ secrets.MICROSERVICE }}
          ADMIN_TOKEN: ${{ secrets.ADMIN_TOKEN }}