name: "Build and deploy to microservice"

on:
  push:
    branches:
      - 'staging'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: nikolaik/python-nodejs:python3.9-nodejs18-slim
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Install deps
        run: |
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
      - name: Build and deploy
        run: npm run build-docker
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          REGION: eu-west-1
          IMAGE: jbtest:${{ steps.extract_branch.outputs.branch }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          MICROSERVICE: ${{ secrets.MICROSERVICE }}
          ADMIN_TOKEN: ${{ secrets.ADMIN_TOKEN }}

          

