name: "Build and deploy to microservice"

on:
  push:
    branches:
      - 'staging'

jobs:
  unit_test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.6.0
        with:
          node-version: 18
      - name: Install deps and test
        run: |
            yarn --frozen-lockfile
            yarn test
  build: 
    needs: unit_test
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.6.0
        with:
          node-version: 18
      - uses: unfor19/install-aws-cli-action@v1
      - uses: actions-hub/docker/cli@master
        env:
          SKIP_LOGIN: true
      - name: Build image
        run: yarn build-docker
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          REGION: eu-west-1
          IMAGE: jbtest:staging-${{github.run_number}}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  deployment:
    name: Deploy to microservice
    needs: build
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.6.0
        with:
          node-version: 18
      - run: yarn --frozen-lockfile
      - name: Deploy
        run: yarn deploy
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          REGION: eu-west-1
          IMAGE: jbtest:staging-${{github.run_number}}
          MICROSERVICE: ${{ secrets.MICROSERVICE }}
          ADMIN_TOKEN: ${{ secrets.ADMIN_TOKEN }}
          TENANT_URL: ${{ vars.TENANT_URL }}
  playwright-test:
    name: Run Playwright tests
    needs: deployment
    environment: staging
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.31.0-focal
    steps:
      - name: Prepare testing env
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3.6.0
        with:
          node-version: 18
      - run: yarn --frozen-lockfile
      - name: Run tests
        run: HOME=/root yarn test:e2e
        env: 
          BASE_URL: ${{ vars.BASE_URL }}